name: 'Setup Canarycage'
description: 'Download and add cage to the PATH'
author: 'LoiLo'
inputs:
  cage-version:
    description: 'Cage version'
    default: '3.4.0'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'